# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn, lib }:

buildGoPackage rec {
  name = "mcdex-unstable-${version}";
  version = "2019-05-26";
  rev = "0fbe62784fa2c7a9d3e4d8a6ffed2b72f73ab0d8";

  goPackagePath = "github.com/dizzyd/mcdex";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/dizzyd/mcdex";
    sha256 = "1gxr6hs88jck42rc0v0grwcpm23ygr3nipxhkyl21rcyj4f449h4";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
    license = lib.licenses.asl20;
  };
}
