# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/Jeffail/gabs";
    fetch = {
      type = "git";
      url = "https://github.com/Jeffail/gabs";
      rev = "636cf72d5e3c0ebad157af7c694469e7d89cec0f";
      sha256 = "159r34pfxdzpsknk1sfcw4m2i8n2hm2sbd9vqfpgjh6z9f1hpbv5";
    };
  }
  {
    goPackagePath = "github.com/PuerkitoBio/goquery";
    fetch = {
      type = "git";
      url = "https://github.com/PuerkitoBio/goquery";
      rev = "3dcf72e6c17f694381a21592651ca1464ded0e10";
      sha256 = "0fpsf6b54z33a7zl28x860jbaj3g5722g8kpqs6rdpaqv99yyvnn";
    };
  }
  {
    goPackagePath = "github.com/andybalholm/cascadia";
    fetch = {
      type = "git";
      url = "https://github.com/andybalholm/cascadia";
      rev = "680b6a57bda4f657485ad44bdea42342ead737bc";
      sha256 = "0v95plagirbjlc4p00y9brhpvv4nm8q0gr63gcfs3shyh1a8xwbm";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-sqlite3";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-sqlite3";
      rev = "070b17a2fdf5109d2dd54acb6bbfb507872115cf";
      sha256 = "0nsj4r3l4yagv5cdn5bnqf7mw6f6bac46d6kfx7qdfp3r04g9jh5";
    };
  }
  {
    goPackagePath = "github.com/robertkrimen/otto";
    fetch = {
      type = "git";
      url = "https://github.com/robertkrimen/otto";
      rev = "15f95af6e78dcd2030d8195a138bd88d4f403546";
      sha256 = "07j7l340lmqwpfscwyb8llk3k37flvs20a4a8vzc85f16xyd9npf";
    };
  }
  {
    goPackagePath = "github.com/viki-org/dnscache";
    fetch = {
      type = "git";
      url = "https://github.com/viki-org/dnscache";
      rev = "c70c1f23c5d84ab39054ec6b418a5ed0fa51cade";
      sha256 = "0k9p3v3df1y1l85xhh5k8wsnidhxx7qyqpyfka1pcs1562q35l97";
    };
  }
  {
    goPackagePath = "github.com/xeonx/timeago";
    fetch = {
      type = "git";
      url = "https://github.com/xeonx/timeago";
      rev = "4e7d8c1f9a433881f64a7f87f51e494186857982";
      sha256 = "1hwhg96s6127w15l39mpil4k4r8zi1zwp02fqgq2vvcyivfm9hgf";
    };
  }
  {
    goPackagePath = "github.com/xi2/xz";
    fetch = {
      type = "git";
      url = "https://github.com/xi2/xz";
      rev = "48954b6210f8d154cb5f8484d3a3e1f83489309e";
      sha256 = "178r0fa2dpzxf0sabs7dn0c8fa7vs87zlxk6spkn374ls9pir7nq";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "f3200d17e092c607f615320ecaad13d87ad9a2b3";
      sha256 = "1mskh7p80dd8j1ffy16917d3cyy7lfh1gb56n4rq9g1bwckz4lwy";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "342b2e1fbaa52c93f31447ad2c6abc048c63e475";
      sha256 = "0flv9idw0jm5nm8lx25xqanbkqgfiym6619w575p7nrdh0riqwqh";
    };
  }
  {
    goPackagePath = "gopkg.in/sourcemap.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/sourcemap.v1";
      rev = "6e83acea0053641eff084973fee085f0c193c61a";
      sha256 = "08rf2dl13hbnm3fq2cm0nnsspy9fhf922ln23cz5463cv7h62as4";
    };
  }
]
