# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/20409297-abc2-4d9f-8c10-6e6b3fbe2df4";
      fsType = "f2fs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/583d3587-bd99-4370-9681-16eee44a0546"; }
    ];

  nix.settings.max-jobs = lib.mkDefault 12;
}
