# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoModule, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoModule rec {
  name = "cli-unstable-${version}";
  version = "2019-01-06";
  rev = "a86f82974270d2da2090a02437560897a216abc3";

  goPackagePath = "github.com/exercism/cli";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/exercism/cli";
    sha256 = "05mb25188vrmwg6i3iqafq31mhrw56m3yaxz4xm94kb4yr18z5ba";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
